test: add e2e workflow and clean up others

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,3 +40,58 @@ jobs:
       - name: Test
         id: pnpm-ci-test
         run: pnpm ci-test
+
+  check-dist:
+    name: Check dist/
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v7.0.1
+
+      - name: Setup PNPM and Install Deps
+        id: setup-pnpm
+        uses: pnpm/setup@v2.0.2
+        with:
+          cache: true
+          version: 11
+          runtime: node@24
+
+      - name: Remove dist/ Directory
+        id: remove-dist
+        run: rm -rf ./dist
+
+      - name: Install Dependencies
+        id: install
+        run: pnpm ci
+
+      - name: Build dist/ Directory
+        id: build
+        run: pnpm bundle
+
+      # This will fail the workflow if the `dist/` directory is different than
+      # expected.
+      - name: Compare Directories
+        id: diff
+        run: |
+          if [ ! -d dist/ ]; then
+            echo "Expected dist/ directory does not exist.  See status below:"
+            ls -la ./
+            exit 1
+          fi
+          if ! git diff --exit-code dist/;  then
+            echo "Detected uncommitted changes after build. See status below:"
+            git diff --ignore-space-at-eol --text dist/
+            exit 1
+          fi
+
+      # If `dist/` was different than expected, upload the expected version as a
+      # workflow artifact.
+      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
+        name: Upload Artifact
+        id: upload
+        uses: actions/upload-artifact@v7.0.1
+        with:
+          name: dist
+          path: dist/
